"""FastMCP application instance for perfmon-mcp.

Every tool module imports ``mcp`` from here and decorates its functions
with ``@mcp.tool()`` at import time, so ``server.py`` only needs to
import the submodules in the right order.
"""

from mcp.server.fastmcp import FastMCP

mcp = FastMCP(
    "perfmon-mcp",
    instructions=(
        "Capture and analyze Windows performance counters (PDH). Workflow "
        "is one of: discover, live snapshot, capture-to-blg, or "
        "load-and-analyze. Tools are transport-agnostic -- run live "
        "commands locally, or call any tool with `target='remote'` to "
        "get the LabLink-first runbook + a JSON sidecar block. Preferred "
        "remote dispatch is `lablink.execute_command`/`lablink.execute_script`; "
        "PSRemoting and manual paste are fallbacks. Always feed the "
        "stdout back to the matching `parse_*_output` tool to render "
        "the same markdown the local path would have produced.\n"
        "\n"
        "DISCOVER: `list_counter_profiles` returns the bundled scenarios "
        "(`system-overview`, `cpu-detailed`, `mellanox-rss`, "
        "`mellanox-percpu`). `get_counter_profile(scenario)` returns the "
        "counter list and overhead notes for one. `discover_counter_sets("
        "target, vendor_filter)` enumerates installed PDH counter sets "
        "(vendor-tagged Mellanox/Intel/Broadcom/Microsoft/Other). "
        "`discover_counter_instances(set_name, instance_filter, target)` "
        "enumerates the per-instance paths under one counter set (use to "
        "verify the right `Adapter #N` literal before capture). "
        "`discover_nics(target)` lists Network Adapters. The "
        "mellanox-percpu profile has a known ~28pp delivery cost at 400K "
        "offered load -- use it for diagnostic distribution analysis, "
        "never for perf baselines.\n"
        "\n"
        "SNAPSHOT (live PDH read, one sample): "
        "`snapshot_counters(scenario, target='local'|'remote')`. Local "
        "spawns Get-Counter and returns a markdown table. Remote returns "
        "the LabLink-first runbook with the Get-Counter command and a "
        "JSON sidecar; feed the remote stdout back to "
        "`parse_counter_output(text, scenario)`.\n"
        "\n"
        "CAPTURE (long-running, emit-only): "
        "`get_capture_commands(scenario, output_path, duration_s, "
        "instance_filter)` returns paste-ready 6-step logman (create + "
        "start/sleep/stop + relog + teardown + verify). The optional "
        "`instance_filter` narrows mellanox-percpu per-instance "
        "enumeration; when omitted, the profile's "
        "`default_instance_filter` is used (mellanox-percpu defaults to "
        "'Adapter #2'). `get_capture_instructions(scenario, target, "
        "output_path, instance_filter)` returns the full runbook "
        "including remote transfer-back examples (LabLink preferred, "
        "PSRemoting and scp as fallbacks). `get_capture_status(target)` "
        "wraps `logman query`; feed the stdout to "
        "`parse_capture_status_output(text)`. `get_teardown_commands("
        "collector_name, target)` emits a force-cleanup runbook (stop + "
        "delete + Stop-Process for any straggler perfmon/typeperf/relog "
        "processes); feed the stdout to `parse_teardown_output(text, "
        "collector_name)`. Capture tools never execute.\n"
        "\n"
        "ANALYZE (after a .blg or .csv exists locally): `load_log(path)` "
        "returns a `log_id`; pass it to every analysis tool. `load_csv("
        "path)` skips relog for plain .csv inputs. `load_blg` is kept as "
        "a deprecated alias of `load_log`. `list_loaded_logs`, "
        "`log_info(log_id)`, `unload_log(log_id)`, and `list_blgs("
        "directory, pattern)` cover registry / metadata / discovery. "
        "`analyze(log_id, sections)` is the mega-tool that returns "
        "summary + timeline highlights + per-queue overview in one call. "
        "Per-section: `get_counter_summary(log_id, top_n)`, "
        "`get_counter_timeline(log_id, counter, bucket_seconds, "
        "max_rows)`, `compute_rate_from_counter(log_id, counter_filter, "
        "interval_s)` (per-counter rate for monotonic raw totals), "
        "`get_per_queue_summary(log_id, queue_filter)` (now surfaces "
        "Delta/Hot/Idle peer-group flags + footer summary), "
        "`get_counter_throughput(log_id, nic_filter, top_n)` (NIC "
        "throughput lens), `get_rss_distribution(log_id, adapter_filter, "
        "scenario_hint)` (per-CPU + per-RqNum + per-SqNum view scoped to "
        "the 13 curated Mellanox WinOF-2 RSS counters), "
        "`compare_logs(baseline_log_id, test_log_id, top_n, "
        "mode='counter'|'per_queue'|'per_cpu')`.\n"
        "\n"
        "FEDERATION (optional, off by default): "
        "`get_evidence_status` reports whether the evidence-store "
        "library is installed AND `PERFMON_MCP_EVIDENCE_PATH` is set. "
        "`get_entities(log_id, entity_type, filter, max_rows)` lists "
        "registered entities; returns a friendly message when "
        "federation is disabled."
    ),
)
